### PR TITLE
Serialize causes when handling exceptions

### LINKED ISSUE #10: Exceptions: Store cause as well
When attaching exceptions to traces, let's also store their `cause`s and their messages (and their causes, and so on...)

[Rails' own `ExceptionWrapper`](https://github.com/rails/rails/blob/0f39a7488ed736a76cc6cee166fba01d1e3c5686/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb) may serve as inspiration.

### PR DESCRIPTION
**Pull request by franzliedke**
Fixes #10.

### CODE REVIEW

File: spec/mnemosyne/trace_spec.rb [hunk 1]
```diff
@@ -85,6 +85,33 @@
...
+
+        it 'serializes the entire exception hierarchy' do
+          is_expected.to match [
+            hash_including(
+              type: 'RuntimeError',
+              text: 'outer',
+              cause: hash_including(
+                type: 'RuntimeError',
+                text: 'inner',
+              ),
```
Comment (franzliedke) [inline spec/mnemosyne/trace_spec.rb]: Is this a desirable format? (It should work recursively, too.)
